client_homepage:
    path:     /Client
    defaults: { _controller: UtilisateursBundle:Client:register }

moniteur_homepage:
    path:     /Moniteur
    defaults: { _controller: UtilisateursBundle:Moniteur:register }
