<?php

namespace Permisfute\PermisfuteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Exam_codeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Exam_codeRepository extends EntityRepository
{
}
