<?php

namespace Permisfute\PermisfuteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExamenPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamenPRepository extends EntityRepository
{
}
