<?php

namespace Permisfute\PermisfuteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LeconRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeconRepository extends EntityRepository
{
}
