<?php

namespace Permisfute\PermisfuteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlanningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanningRepository extends EntityRepository
{
}
