# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    
    calendar_event.test:
        class: ADesigns\CalendarBundle\Tests\Fixtures\EventListener\CalendarEventListener
        tags:
            - { name: kernel.event_listener, event: calendar.load_events, method: loadEvents }
