<?php

namespace Permisfute\PermisfuteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Type_examRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_examRepository extends EntityRepository
{
}
